# Generated by Django 2.2.9 on 2022-12-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221206_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.Group'),
        ),
    ]
